mods to bin/testprog
so it can run & compare prt tests

diff --git a/bin/testprog b/bin/testprog
--- a/bin/testprog
+++ b/bin/testprog
@@ -38,29 +38,34 @@ then
 
 fi
 
-if [ ! -f $1.cmp ]
-then
-
-   echo "*** Error: Compare file $1.cmp does not exist"
-   exit 1
-
-fi
-
 echo -n "Compiling $1 ... "
-compile $1
-rc=$?
-if [[ $rc = 0 ]]
+compile $1 > /dev/null
+if [ $? -eq 0 ]
 then
+
+    if [ ! -f $1.cmp ]
+    then
+        echo "*** Error: Compare file $1.cmp does not exist"
+        exit 1
+    fi
 
     echo -n "running ... "; run $1
     echo -n "checking ... "; diffnole $1.lst $1.cmp > $1.dif
 
-    ## pass if diff file is empty
-    if test -s "$1.dif"; then
-       echo FAIL
-    else
-       echo PASS
-    fi
 else
-    echo FAIL
+    if [ ! -f $1.ecp ]
+    then
+        echo "*** Error: Compare file $1.ecp does not exist"
+        exit 1
+    fi
+
+    echo -n "Checking compilation ... "
+    diffnole $1.err $1.ecp > $1.dif
+fi
+
+## pass if diff file is empty
+if test -s "$1.dif"; then
+   echo FAIL
+else
+   echo PASS
 fi
