Various mods to bring bash environment up to speed:
1. Compile script uses new prd input format for prd.

2. Compile converts error output in listing to error return code.

3. Run script uses new directory structure.

4. Simplication to run script (rm -f).

5. testprog script only runs if compile is error free.

6. testprog only lists lines with .diff, I don't remember why that is
required.

diff --git a/gpc/compile b/gpc/compile
--- a/gpc/compile
+++ b/gpc/compile
@@ -33,5 +33,21 @@ then
    exit 1
 fi
 
-pcom < $1.pas > $1.err
+cp $1.pas prd
+pcom > $1.err
+#
+# The status of the compile is not returned, so convert a non-zero
+# error message to fail status
+#
+grep -q "Errors in program: 0" $1.err
+rc=$?
+if [[ $rc != 0 ]] ; then
+
+    exit 1
+        
+fi
+#
+# Move the prr file to <file.p5>
+#
+rm -f $1.p5
 mv prr $1.p5
